INSERT INTO clients (lastname, firstname, mail, password) VALUES 
('Lara', 'Ed', 'ed.lara@gmail.com', 'webprog');

INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (1,'Moth orchid',54,'This elegant orchid produces graceful spikes crowned with showy flowers that are an excellent focal plant for containers or hanging baskets.','Flower',8);
INSERT INTO plants  (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (2,'Fairy Castle Cactus',33.85,'This cactus has quaint branches dressed in delicate spikes that grow to resemble castle spires fit for fairy godmothers and princesses alike. It\'s a fuss-free plant, requiring the bare minimum to thrive. The perfect fit for a busy lifestyle; consider it magic.','Cactus',13);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (3,'Golden Barrel Cactus',27.2,'Also known as Echinocactus Grussoni. This beautiful golden spined barrel cactus grows to be 2\' feet tall x 3 feet wide and is striking in a pot or in a landscape. Yellow flowers bloom in the Summer. Cold hardy to the mid twenties.','Cactus',16);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (4,'Venus Flytrap',19.5,'Venus fly trap \'B52\' is in a class of its own. Venus flytrap \'B52\' grows massive, bright red traps with unusually long teeth. These Dionaea Muscipula are vigorous growers, and produce a large number of traps.  There is very high demand for these plants, so snap them up while you can! ','Carnivorous',5);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (5,'Passionate Purple Tulips ',38,'Tulips this tantalizing need no decoration! Celebrate a spring birthday, send your love, or simply let someone know you\'re thinking of them with this stunning monochrome bouquet. Presented in a clear cylinder vase, the minimalist gift appeals to purple-lovers, tulip-devotees and those with a more elegant and simple sense of style.','Flower',28);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (6,'Juniper Bonsai',52,'This captivating Rock Juniper Bonsai tree features the power and tranquility of Bonsai but in a smaller size. If space is a limitation, this juniper bonsai tree can add color and harmony while still possessing all the characteristics of its larger version. ','Tree',20);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (7,'Cactus Dish Garden',76.99,'Bring a touch of Southwestern charm to any home décor with our easy-to-care-for cactus dish garden. A collection of assorted cacti and succulents come together in a charming Pueblo-design pot, creating a unique desert gardenscape alive with eye-catching texture and color.','Cactus',37);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (8,'Orange Mum Plant ',42.5,'A fall favorite, our lush blooming mum is sure to delight. Vibrant orange blooms arrive designed in our rustic, farm stand-inspired planter to complete its seasonal charm. Bring home the seasonal scent of spiced pumpkin by adding our Yankee Candle® to your gift.','Flower',51);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (9,'Phalaenopsis orchid',60,'Rare and exotic, our blue Phalaenopsis orchid is simply captivating. Designed with a specially enhanced bloom color, it arrives in a brown woven basket for a unique presentation. Pair it with a delicate crystal wind chime for a gift of true serenity.','Flower',11);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (10,'Dracaena massangeana',119.99,'Dracaena massangeana, or dracaena fragrance, is also known as \"corn plant\".  It has long graceful green leaves have yellow and light green stripe running down the center, which grow out of a central woody stalk, much like a real corn stalk. ','Cane plant',13);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (11,'Orpheus',80.85,'Offer the recipient a pure moment of joy with this arrangment mixing red and white reuniting roses and lilies. A romantic and sentimental bouquet completed by eucalyptus that will surely add a flowery touch to all your occasions.','Flower',8);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (12,'Drosera',10.99,'Drosera venusta is a spectacular sundew native to South Africa. The wide, semi-erect leaves are a vivid red-orange color with bright red tendrils and copious droplets of dew used to catch preys. Because of their compact growth tendency, these make fantastic terrarium specimens.','Carnivorous',17);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (13,'Palm',26.98,'The crown jewel of the Palm family, Majesty Palm has a classic look that adds a touch of elegance indoors or out. It is a native of the Madagascar jungle so it’s important to keep the plant from drying out. This upright plant adds instant beauty to any home, apartment, or office. It is shipped in a black decorative planter. Use it to fill empty corners in your home or line up several as a living screen or room divider.','Cane plant',23);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (14,'Nephentes',16.99,'The plant we call Nepenthes \"Love\" has consistently produced plants with lots of color, both in the pitchers and the leaves. A sweet scent emanes from the pitch and it\'s tendency to grow in a rather small space make it an ideal plant to horn your interior.','Carnivorous',39);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (15,'Nagami Kumquat Tree',89.95,'With our Nagami Kumquat Tree, you\'ll have your own sweet, juicy kumquats from home. Especially since the Nagami couldn\'t be simpler to grow because it\'s drought-tolerant, and pest and disease resistant.','Fruit plant',3);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (16,'Satsuki Azalea',49.05,'This flowering bonsai produces blooms during the spring and possibly during the fall with the proper care. Its blush (pink) blooms can add a refreshing touch to a room looking for natural color.','Tree',12);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (17,'Blueberry Bush',29.95,'The Pink Lemonade Blueberry is firm, juicy, sweet, and has been said to have a slight hint of kiwi flavor. While most blueberries harvest all at once, this one will peak in late summer and continue to produce delicious berries through October. They\'ll turn pink when they\'re ready to be picked and are so delicious right off the vine.','Fruit plant',25);
INSERT INTO plants (`idplants`,`name`,`price`,`description`,`type`,`stock`) VALUES (18,'Red  Hydrangea',69.99,'The Red Sensation Hydrangea is the only reblooming variety that delivers rich, vibrant red flowers. And not only do you get unbelievable, unique red color from your Red Sensation...but you also get giant blooms that explode with bright red color for weeks at a time.','Flower',13);
